CREATE TABLE Incidents(
      INCIDENT_ID int PRIMARY KEY AUTO_INCREMENT,
      NAME VARCHAR(20) not null,
      TYPE VARCHAR(20) not null,
      DISTANCE VARCHAR(20) not null
      );


ALTER TABLE Incidents
    ADD HIGHWAY_ID int(10),
    ADD CONSTRAINT FK_HIGHWAY_ID FOREIGN KEY (HIGHWAY_ID) REFERENCES HIGHWAYS(HIGHWAY_ID);